[package]
name = "hello-world"
version = "0.1.0"
authors = ["Unknow <unknow@unknow.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
serde_json = "1.0.53"
handlebars = { version = "3.0.1", features = ["dir_source"]}