[package]
name = "chapter_five"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]

[dependencies]
lazy_static = "1.0"
regex = "0.2"
bitflags = "1.0"
chapter-five-derive = { path = "chapter-five-derive" }
env_logger = "0.5.3"
log = "0.4.1"

